### ISSUE TITLE
Watermeter offset?

### ISSUE THREAD

**Issue by hubertjanhickinson** [jvandenaardweg/homewizard-energy-api#99]
According to this post (https://gathering.tweakers.net/forum/list_message/72550118#72550118) it is possible to set the offset of the watermeter. Do you have any idea how to do that using a simple API request in Postman?

**Comment by jvandenaardweg** [comment]
@hubertjanhickinson just had a look at the official API documentation here: https://homewizard-energy-api.readthedocs.io/endpoints.html#data-points-for-hwe-wtr

It seems there's a option to request the `total_liter_offset_m3` datapoint. But also states: "The usage of this value is in development and should not be used". Also, there's no documentation on how to change that value with their API.

Maybe this option is configurable within the Energy iOS/Android app?

Just noticed my package was missing the `total_liter_offset_m3` in the response types. To fix that I just created a new release: https://github.com/jvandenaardweg/homewizard-energy-api/releases/tag/1.5.0

Other than this, I don't know how to support changing the `total_liter_offset_m3` value through my npm package or using Postman, because there is no documentation for it.
